### ISSUE TITLE
About jacobi

### ISSUE THREAD

**Issue by rlczddl** [rFalque/embedded_deformation#2]
Hi, I can't figure out the derivative formula used in the file of costFunction.hpp, can you give me some references about this,especially for formula 8) in the paper?

**Comment by rFalque** [comment]
Hi @rlczddl , I derived most of it by hand, equation 8 is defined there: https://github.com/rFalque/embedded_deformation/blob/63ea6e0960d4beb96a0e0528705b91dafd14bed3/embedded_deformation/include/embedded_deformation/costFunction.hpp#L530

If you want to implement your own cost function, I highly recommend you the autodiff from CERES, it works really well. The time difference with a provided jacobian is marginal in many situations.

**Comment by rlczddl** [comment]
Thanks for your answer. I also successfully derived the jacobian matrix by hand. The residual term of this algorithm is relatively simple and easy to deduce and I would like to ask if there is any skill in deriving jacobian matrix for complex residual terms?

**Comment by rFalque** [comment]
I like that website [http://www.matrixcalculus.org/](http://www.matrixcalculus.org/). You can export code in python and kind of translate it for Eigen.

Otherwise, Matlab and Python have tools for doing so. Still, I highly recommend you to give a try to this [http://ceres-solver.org/automatic_derivatives.html](http://ceres-solver.org/automatic_derivatives.html) ;)

**Comment by rlczddl** [comment]
Thank you again. I'll get to know what you said.
