### ISSUE TITLE
about build graph connectivity

### ISSUE THREAD

**Issue by rlczddl** [rFalque/embedded_deformation#3]
Hello, I don't quite understand the implementation logic of this function. Can you tell me the implementation idea of this function? Is the function of this function just to find the nearest k graph nodes along the edge of the mesh?This question may be a bit stupid.

https://github.com/rFalque/embedded_deformation/blob/63ea6e0960d4beb96a0e0528705b91dafd14bed3/embedded_deformation/src/embedded_deformation/greedySearch.cpp#L54

**Comment by rFalque** [comment]
Yes, you are absolutely correct. It performs a Dijkstra search kind of thing until it reaches k nodes on a given mesh. That allows to use the manifold and avoid connecting points that are close but not connected. This is kind of irrelevant to be honest because if you have a mesh you might want to use ARAP as an alternative ;)

I just happen to have meshes in some of my experiments.

**Comment by rFalque** [comment]
Just as a clarification it does not search on the graph but on a mesh, the aim is to build a graph or to find the closest neighbours when you apply the morphing after the optimisation ;)

**Comment by rlczddl** [comment]
Thank you for your quick answer, I understand now!
